name: Build, Test, and Push to DockerHub & GHCR

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [frontend, backend]

    concurrency:
      group: "ci-build-${{ matrix.service }}"
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        if: matrix.service == 'backend'
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run unit tests and linting
        if: matrix.service == 'backend'
        run: |
          pip install pytest flake8 httpx
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest backend/tests --junitxml=test-results.xml || true
          flake8 backend

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/feedback-${{ matrix.service }}:latest ./${{ matrix.service }}
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/feedback-${{ matrix.service }}:latest ./${{ matrix.service }}

      - name: Security scan using Trivy
        uses: aquasecurity/trivy-action@0.11.2
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/feedback-${{ matrix.service }}:latest
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GH_PAT }}

      - name: Push to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/feedback-${{ matrix.service }}:latest

      - name: Push to GHCR
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/feedback-${{ matrix.service }}:latest

  wait-for-qa:
    needs: build-and-push
    runs-on: ubuntu-latest
    concurrency:
      group: "wait-for-qa-${{ github.sha }}"
      cancel-in-progress: true
    environment:
      name: qa-approval
      url: https://qa.example.com
    steps:
      - name: Pause for QA approval
        run: echo "🛑 Waiting for QA to approve..."

      - name: Notify Slack - QA Approval Requested
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "🧪 *QA Approval Needed!*\n> Commit: `${{ github.sha }}`\n> Repo: `${{ github.repository }}`\n> [Click here to approve in GitHub Actions](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          }' ${{ secrets.SLACK_WEBHOOK_URL_QA }}


  deploy-prod:
    needs: wait-for-qa
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://prod.example.com
    steps:
      - name: Deploy to Production
        run: |
          echo "🚀 Deploying to production..."
          # Add actual deployment script here
          # e.g. terraform apply or aws ecs update-service

      - name: Notify Slack - Production Deployed
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "✅ *Deployment Successful!*\n> Service: `${{ github.repository }}`\n> Commit: `${{ github.sha }}`\n> Env: *production*"
          }' ${{ secrets.LACK_WEBHOOK_URL_PROD }}
#