name: Build, Test, and Push to DockerHub & GHCR

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [frontend, backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          if [ "${{ matrix.service }}" = "backend" ]; then
            pip install -r backend/requirements.txt
          fi
          echo "✅ Dependencies installed"

      - name: Run unit tests and linting
        run: |
          if [ "${{ matrix.service }}" = "backend" ]; then
            pip install pytest flake8
            pytest backend/tests --junitxml=test-results.xml
            flake8 backend --exit-zero
          fi
          echo "✅ Tests and lint passed"

      - name: Security scan using Trivy
        uses: aquasecurity/trivy-action@v0.14.1
        with:
          image-ref: 'feedback-${{ matrix.service }}:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GH_PAT }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/feedback-${{ matrix.service }}:latest ./${{ matrix.service }}
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/feedback-${{ matrix.service }}:latest ./${{ matrix.service }}

      - name: Push to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/feedback-${{ matrix.service }}:latest

      - name: Push to GHCR
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/feedback-${{ matrix.service }}:latest
